{% set name = "napari-meshio" %}
{% set version = "0.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 489bdfba46fe12b82e404f6bbcc8056f508fec034b84ac64767817afcd9b0e09

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - meshio
    - numpy
    - pooch
    - python >=3.8
    - rich

test:
  imports:
    - napari_meshio
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/GenevieveBuckley/napari-meshio
  summary: I/O for mesh files.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - GenevieveBuckley
    - goanpeca
    - jaimergp
