{% set name = "napari-meshio" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/napari-meshio-{{ version }}.tar.gz
  sha256: 6aa88005a2316e03895a9397c949b7cae01d3966fb6db0f288c53998964c7108

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools-scm
  run:
    - meshio
    - numpy
    - pooch
    - python >={{ python_min }}
    - rich

test:
  imports:
    - napari_meshio
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/GenevieveBuckley/napari-meshio
  summary: I/O for mesh files.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - GenevieveBuckley
    - goanpeca
    - jaimergp
